specVersion: 0.0.1
description: "A subquery project provide common api for a substrate based network\e[D\e[D\e[D\e[D\e[D\e[D\e[D\e[D"
repository: ''
schema: ./schema.graphql
network:
  endpoint: 'wss://polkadot.api.onfinality.io/public-ws'
dataSources:
  - name: main
    kind: substrate/Runtime
    startBlock: 1
    mapping:
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
        - handler: handleCall
          kind: substrate/CallHandler
        - handler: handleAccount
          kind: substrate/EventHandler
          filter:
            module: identity


